name: Build and Test

on:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        if: runner.os != 'Windows'
        run: |
          curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt-get install -y nodejs
        shell: bash

      - name: Install Node.js (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install node
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.4
          cache: 'pip'
          install-dir: ${{ runner.temp }}/python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build with PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller phototransductsim.spec

      - name: Copy files to output directory
        run: |
          mkdir -p /mnt/output/dist
          cp -r dist/* /mnt/output/dist

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: phototransductsim-${{ matrix.os }}
          path: dist/

  release-test:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: phototransductsim-windows-latest
          path: dist/windows

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: phototransductsim-macos-latest
          path: dist/macos

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: phototransductsim-ubuntu-latest
          path: dist/linux
