name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build with PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller phototransductsim.spec

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: phototransductsim-${{ matrix.os }}
          path: dist/

  release-test:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: phototransductsim-windows-latest
          path: dist/windows

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: phototransductsim-macos-latest
          path: dist/macos

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: phototransductsim-ubuntu-latest
          path: dist/linux

