name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install poetry
          poetry install
          pip install pyinstaller zstandard

      - name: Build with PyInstaller
        run: |
          python -m PyInstaller phototransductsim.spec

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: phototransductsim-${{ matrix.os }}
          path: dist/

  create_installer_windows:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: phototransductsim-windows-latest
          path: dist/

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: phototransductsim.iss
          options: /O+

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: phototransductsim-windows-installer
          path: dist/PhototransductSimInstaller.exe

  create_installer_macos:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: phototransductsim-macos-latest
          path: dist/

      - name: Create macOS DMG
        run: |
          hdiutil create -volname PhototransductSim -srcfolder dist/phototransductsim -ov -format UDZO dist/phototransductsim.dmg

      - name: Upload macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: phototransductsim-macos-installer
          path: dist/phototransductsim.dmg

  release:
    needs: [create_installer_windows, create_installer_macos]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.PERSONAL_TOKEN}}
          exclude_types: other,doc,chore

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          prerelease: false

      - name: Download Windows Installer
        uses: actions/download-artifact@v4
        with:
          name: phototransductsim-windows-installer
          path: dist/

      - name: Download macOS DMG
        uses: actions/download-artifact@v4
        with:
          name: phototransductsim-macos-installer
          path: dist/

      - name: Upload Windows Installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/PhototransductSimInstaller.exe
          asset_name: PhototransductSimInstaller.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Upload macOS DMG
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/phototransductsim.dmg
          asset_name: phototransductsim.dmg
          asset_content_type: application/x-apple-diskimage
